package com.example.notes.data

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "user_table")
data class User(
    @PrimaryKey(autoGenerate = true)
    val id: Int, // primary key which is automatically generated by room library
    val firstName: String,
    val lastName: String,
    val age: Int
)